# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_for_tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('track_title_picture', models.FileField(default='media', upload_to=b'')),
                ('track_type', models.CharField(max_length=100)),
                ('track_adress', models.CharField(max_length=200)),
                ('track_information', models.TextField(max_length=10000)),
                ('track_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures_for_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='media', upload_to=b'')),
                ('parent_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_map.Model_for_tracks')),
            ],
        ),
    ]
