# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_db',
            fields=[
                ('track_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('parent_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_map.Model_for_tracks')),
            ],
        ),
    ]
