# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_map', '0003_auto_20170207_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_for_tracks',
            name='track_type',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
