# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_map', '0004_model_for_tracks_track_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_for_tracks',
            name='track_type',
        ),
    ]
