# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_map', '0007_types_of_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureForTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='media', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_picture', models.FileField(default='media', upload_to=b'')),
                ('address', models.CharField(max_length=200)),
                ('information', models.TextField(max_length=10000)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='track_map.Track')),
            ],
        ),
        migrations.RenameModel(
            old_name='Types_db',
            new_name='TypesDB',
        ),
        migrations.RemoveField(
            model_name='model_for_tracks',
            name='track_type',
        ),
        migrations.RemoveField(
            model_name='pictures_for_track',
            name='parent_track',
        ),
        migrations.RemoveField(
            model_name='types_of_tracks',
            name='parent_track',
        ),
        migrations.RemoveField(
            model_name='types_of_tracks',
            name='track_type',
        ),
        migrations.DeleteModel(
            name='Model_for_tracks',
        ),
        migrations.DeleteModel(
            name='Pictures_for_track',
        ),
        migrations.DeleteModel(
            name='Types_of_tracks',
        ),
        migrations.AddField(
            model_name='typesoftrack',
            name='track_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_map.TypesDB'),
        ),
        migrations.AddField(
            model_name='track',
            name='type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='track_map.TypesDB'),
        ),
        migrations.AddField(
            model_name='picturefortrack',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_map.Track'),
        ),
    ]
