# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_picture', models.FileField(upload_to=b'')),
                ('news_title', models.CharField(max_length=100)),
                ('news_posting_time', models.CharField(max_length=30)),
                ('news_anotation', models.CharField(max_length=200)),
                ('news_text', models.CharField(max_length=10000)),
                ('news_views_count', models.CharField(max_length=10)),
                ('news_comments_count', models.CharField(max_length=10)),
            ],
        ),
    ]
