# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 12:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(blank=True, default='/home/albert/IMG_958.JPG', upload_to='media')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_picture', models.FileField(upload_to=b'')),
                ('slug', models.SlugField(max_length=200)),
                ('posting_time', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=10000)),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PictureForNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='media', upload_to=b'')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NewsPost')),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NewsPost'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AdvancedUser'),
        ),
    ]
