# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
