# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161117_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='news_picture',
            field=models.FileField(default='media', upload_to=b''),
        ),
    ]
