# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_post_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='news_title_url',
            field=models.CharField(default='news_title', max_length=200),
        ),
    ]
