# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_post_news_title_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='news_title_url',
        ),
    ]
