# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_post_news_title_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_anotation',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator]),
        ),
    ]
