# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161118_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_title_url',
            field=models.SlugField(default='news_title', max_length=200),
        ),
    ]
