# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161118_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_posting_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
