# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161121_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='news_post',
            name='news_anotation',
            field=models.CharField(max_length=200),
        ),
    ]
