# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161121_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='news_title_url',
        ),
        migrations.AddField(
            model_name='news_post',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='news_posting_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
