# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161124_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_anotation',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='news_text',
            field=models.TextField(max_length=10000),
        ),
    ]
