# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161124_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
