# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0013_auto_20161124_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('testirovanit', models.CharField(default='test', max_length=100)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='site_users',
            name='avatar',
            field=models.FileField(upload_to='media'),
        ),
    ]
