# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161128_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced_user',
            name='testirovanit',
            field=models.CharField(max_length=100),
        ),
    ]
