# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_site_users_avatar_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_users',
            name='avatar_test',
        ),
        migrations.AddField(
            model_name='advanced_user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
