# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161128_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced_user',
            name='testirovanit',
        ),
    ]
