# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_advanced_user_testirovanit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_users',
            name='avatar',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
