# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('main', '0019_auto_20161202_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced_user',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='site_users',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Advanced_user',
        ),
    ]
