# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_advanced_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced_user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='advanced_user',
            name='testirovanit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
