# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20161202_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_users',
        ),
        migrations.RemoveField(
            model_name='advanced_user',
            name='testirovanit',
        ),
        migrations.AddField(
            model_name='advanced_user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
