# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20161202_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Advanced_user')),
            ],
        ),
    ]
