# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
