# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_test_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_model',
            old_name='user',
            new_name='user_nickname',
        ),
    ]
