# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170117_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_db',
            name='test_user_nickname',
            field=models.ForeignKey(default='common_user', on_delete=django.db.models.deletion.CASCADE, to='main.Advanced_user'),
        ),
    ]
