# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_test_db_test_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_db',
            name='super_test_user_nickname',
            field=models.TextField(default='supertest', max_length=1000),
        ),
    ]
