# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_test_db_super_test_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_db',
            name='test_user_nickname',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Advanced_user'),
        ),
    ]
