# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170121_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_model',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 21, 13, 39, 3, 146308)),
        ),
    ]
