# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_comment_model_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_model',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
