# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170121_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_model',
            old_name='parent_object',
            new_name='article',
        ),
        migrations.AddField(
            model_name='comment_model',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comment_model'),
        ),
    ]
