# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20170131_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_comments_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
