# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20170131_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='news_comments_count',
        ),
        migrations.RemoveField(
            model_name='news_post',
            name='news_views_count',
        ),
    ]
