# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170131_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_views_count',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
