# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170131_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures_for_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='media', upload_to=b'')),
                ('parent_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News_post')),
            ],
        ),
    ]
