# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_pictures_for_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='news_picture',
        ),
    ]
