# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_news_post_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='news_comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
