# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20170131_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures_for_news',
            new_name='Picture_for_news',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_anotation',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_comments_count',
            new_name='comments_count',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_posting_time',
            new_name='posting_time',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_title_picture',
            new_name='title_picture',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='news_views_count',
            new_name='views_count',
        ),
        migrations.RenameField(
            model_name='picture_for_news',
            old_name='parent_news',
            new_name='news_id',
        ),
        migrations.RemoveField(
            model_name='comment_model',
            name='parent',
        ),
    ]
