# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170328_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced_user',
            name='test_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
