# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_advanced_user_test_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced_user',
            name='test_email',
        ),
    ]
