# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_advanced_user_test_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced_user',
            name='avatar',
            field=models.FileField(blank=True, default='/home/albert/IMG_958.JPG', upload_to='media'),
        ),
    ]
